---
title: "Home"
date: "2022-04-27"
output: html_document 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# What is ISoP?
ISoP stands for International Society of Pharmacometrics. The purpose of the ISoP is to promote and advance the discipline of Pharmacometrics and broaden its impact. We are individuals from around the globe from various backgrounds in pharmaceutics, engineering, statistics, and mathematics, who are passionate about advancing and promoting the field of Pharmacometrics.

# What is ASA?
The American Statistical Association (ASA) is the world’s largest community of statisticians, the “Big Tent for Statistics.” It is the second-oldest, continuously operating professional association in the country. Since it was founded in Boston in 1839, the ASA has supported excellence in the development, application, and dissemination of statistical science through meetings, publications, membership services, education, accreditation, and advocacy.

# What are Special Interest Groups (SIGs)?
A Special Interest Group (SIG) is a community with a shared interest in advancing a specific area of knowledge, learning or technology, where members cooperate to affect or to produce solutions within their particular field. The SIGs communicate, meet, develop training materials, develop position papers and publications, support students, and organize programming ideas.

There are four special interest groups.

* Clinical Pharmacometrics SIG   
* Mathematical and Computational Sciences (MCS) SIG  
* Quantitative Systems Pharmacology (QSP) SIG  
* Statistics and Pharmacometrics (SxP) SIG  

# What is SxP SIG?
The Statistics and Pharmacometrics Special Interest Group (SxP) was named in 2016 and is chartered by both the American Statistical Association and International Society of Pharmacometrics.  This Special Interest Group promotes collaboration between Statisticians and Pharmacometricians, to enable each discipline to learn and grow from the other and to develop innovative approaches to model informed drug development.

Specifically, the goals of the SxP SIG are to:

* Provide educational opportunities to learn about Statistics and Pharmacometrics
* Encourage career growth and mentoring for people new in the field
* Promote cross-disciplinary methodology research and publications, and to encourage cross participation at conferences
* Create best practices leveraging both disciplines
* Provide opportunities to discuss computing platforms and share code


# Join Us!
Membership is free. 

Benefits of membership include access to a vast network of professionals from the joint scientific community and access to the content pertaining to scientific lectures, presentations, and related educational materials. SxP will have annual SIG meetings at the ISoP's American Conference on Pharmacometrics (ACoP) and at the ASA’s Joint Statistical Meeting (JSM) and will sponsor sessions at such meetings.


  
  
